version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "${APP_NAME}-api"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/var/www/api
      - "/var/www/api/node_modules"
    env_file: .env
    networks:
      - app-tier
    depends_on:
      - db
      - redis

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-tier
